label: webvh-controller

auto-provision: true

admin: [0.0.0.0, 8020]
admin-insecure-mode: true

inbound-transport:
  - [ws, 0.0.0.0, 8021]
  - [http, 0.0.0.0, 8022]
outbound-transport: [ws, http]
endpoint:
  - http://localhost:4000

plugin:
  - webvh

no-ledger: true

# Wallet
wallet-type: askar-anoncreds
wallet-name: controller-wallet
wallet-key: insecure


log-level: info

auto-accept-invites: true
auto-respond-messages: true

# Plugin
plugin-config-value:
  - did-webvh.server_url=https://sandbox.bcvh.vonx.io